#!/usr/bin/env python
import sys
import getclass


class CLS(object):

    def method(self):
        pass

    @property
    def property(self):
        pass

    @classmethod
    def classmethod(cls, x):
        pass

    @staticmethod
    def staticmethod(x):
        pass


cls = getclass.getclass(sys)
print(cls)
