#!/usr/bin/env python
import getclass

"""
inspect.getmembers python2.6 requires non abstract class
"""


class CLS(object):

    def method(self):
        pass

    @property
    def property(self):
        pass

    @classmethod
    def classmethod(cls, x):
        pass

    @staticmethod
    def staticmethod(x):
        pass


cls = getclass.getclass(CLS)
print(cls)
